# Generated by Django 5.2 on 2025-05-06 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hms_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='lastname',
            new_name='last_name',
        ),
    ]
