# Generated by Django 5.2 on 2025-05-06 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hms_app', '0002_rename_lastname_doctor_last_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='speciality',
            new_name='specialty',
        ),
    ]
