# Generated by Django 5.2 on 2025-05-06 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms_app', '0003_rename_speciality_doctor_specialty'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='patients',
            field=models.ManyToManyField(related_name='doctors', through='hms_app.Appointment', to='hms_app.patient'),
        ),
        migrations.DeleteModel(
            name='PatientDoctor',
        ),
    ]
