# Generated by Django 5.2 on 2025-05-11 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms_app', '0004_doctor_patients_delete_patientdoctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='diagnosis',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='billing',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hms_app.patient'),
        ),
        migrations.AlterField(
            model_name='billing',
            name='payment_status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Pending', 'Pending'), ('Overdue', 'Overdue')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='billing',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialty',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
